fragrance_project/fragrance_project/urls.py
from re import template
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static
# from users.views import NutritionistsListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', user_views.profile, name='profile'),
    path('profile/edit/', user_views.profile_edit, name='profile_edit'),
    path('create-account/', user_views.choose_account, name='choose'),
    path('register/', user_views.register, name='register'),
    # path('register-nutritionist/', user_views.register_nutritionist, name='register_nutritionist'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'),
         name='password_reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
    # path('all-nutritionists/', NutritionistsListView.as_view(), name='nutritionists_list'),
    path('', include('perfume.urls')),
    # path('forum/', include('forum.urls')),
    # path(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
]


if settings.DEBUG:  # allow our media to be accessed from browser
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fragrance_project/perfume/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    PerfumeListView, 
    PerfumeDetailView, 
    PerfumeDeleteView,
    # UserPerfumeListView,
)
from .views import (
    about, 
    perfume_create_view, 
    perfume_update_view, 
    fragrance_view,
    # download
)


urlpatterns = [
    # path('', views.home, name='perfume-home'),
    path('', PerfumeListView.as_view(), name='perfume-home'),
    # path('user/<str:username>', UserPerfumeListView.as_view(), name='user-perfume'),
    path('perfume/<int:pk>/', PerfumeDetailView.as_view(), name='perfume-detail'),
    path('perfume/new/', perfume_create_view, name='perfume-create'),
    path('perfume/<int:pk>/update/', perfume_update_view, name='perfume-update'),
    # path('download/', download, name='download'),
    path('perfume/<int:pk>/delete/', PerfumeDeleteView.as_view(), name='perfume-delete'),
    path('fragrances/', fragrance_view, name='perfume-fragrance'),
    path('about/', about, name='perfume-about'),
    
]

if settings.DEBUG:  # allow our media to be accessed from browser
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fragrance_project/perfume/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from PIL import Image

# Create your models here.
class Fragrance(models.Model):
    name = models.CharField(max_length=255, unique=True)
   
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Perfume(models.Model):
    TARGET_CHOICES = [
        ('men', 'men'),
        ('women', 'women'),
        ('unisex', 'unisex'),
    ]

    name = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    date_posted = models.DateField(default=timezone.now)
    target = models.CharField(max_length=15, choices=TARGET_CHOICES, null=True)

    image = models.ImageField(
        default='default_perfume.png', upload_to='perfume_pics')

    fragrances = models.ManyToManyField(
        Fragrance, through="Perfume_Fragrance")

    
    # hit_count_generic = GenericRelation(HitCount,
    #                                     object_id_field='object_pk',
    #                                     related_query_name='hit_count_generic_relation')  # nr. views

    class Meta:
        ordering = ['-date_posted', 'name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # returns full-path as a string
        return reverse('perfume-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # resize image
        img = Image.open(self.image.path)
        if img.height > 350 or img.width > 400:
            output_size = (350, 400)
            img.thumbnail(output_size)
            img.save(self.image.path)




class Perfume_Fragrance(models.Model):
    UNIT_CHOICES = [
        ('oz', 'ounce'),
        ('ml', 'mililitre'),
        ('l', 'litre'),
        ('g', 'gram')
    ]
    quantity = models.FloatField()
    unit = models.CharField(max_length=15, choices=UNIT_CHOICES, null=True)
    fragrance = models.ForeignKey(Fragrance, on_delete=models.CASCADE)
    perfume = models.ForeignKey(Perfume, on_delete=models.CASCADE)

fragrance_project/perfume/views.py
from django.shortcuts import render

# Create your views here.
from datetime import timedelta, timezone
import os
from gensim.models import word2vec
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
# from django.db.models import Count
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView
)
from .models import Fragrance, Perfume, Perfume_Fragrance
from .forms import PerfumeForm, PerfumeFragranceFormSet
# from hitcount.views import HitCountDetailView


@login_required
def home(request):
    # popular = Perfume.objects.order_by("-hit_count_generic__hits")
    # period = timezone.now() - timedelta(days=30)
    # top_models = Perfume.objects.filter(
    #     hitcounts__hit__created__gte=period
    # ).annotate(
    #     counts=Recipe.Count('hitcounts__hit')
    # ).order_by('-counts')
    context = {
        'perfumes': Perfume.objects.all(),
        # 'popular': top_models,
    }
    return render(request, 'perfume/home.html', context)


class PerfumeListView(LoginRequiredMixin, ListView):  # class based view
    model = Perfume
    # if template_name not given, needs view template with name: <app>/<model>_<viewtype>.html
    template_name = 'perfume/home.html'
    context_object_name = 'perfumes'
    ordering = ['-date_posted']
    paginate_by = 3

    # def get_context_data(self, **kwargs):
        # popular = Recipe.objects.annotate(downloads=Count('download')).order_by(
        #     '-downloads', '-hit_count_generic__hits')[:6]
        # context = super().get_context_data(**kwargs)
        # context.update({
        #     'popular': popular,
        # })
        # return context


# class UserPerfumeListView(LoginRequiredMixin, ListView):  # filtered recipes by user
#     model = Perfume
#     template_name = 'perfume/user_perfume.html'
#     context_object_name = 'perfumes'
#     ordering = ['-date_posted']
#     paginate_by = 3

#     def get_queryset(self):
#         user = get_object_or_404(User, username=self.kwargs.get('username'))
#         return Perfume.objects.filter(author=user).order_by('-date_posted')


class PerfumeDetailView(LoginRequiredMixin, DetailView): #, HitCountDetailView):
    model = Perfume  # template: perfume/perfume_detail.html
    context_object_name = 'rec'
    template_name = 'perfume/perfume_detail.html'
    # set to True to count the hit
    # count_hit = True


# def download(request):
#     if request.method == 'POST':
#         pk = request.POST.get('recipe')
#         rec = get_object_or_404(Recipe, id=pk)
#         download = Download(recipe=rec)
#         download.save()
#     return redirect('perfume-detail', pk)


@login_required
def perfume_create_view(request):
    if request.method == 'POST':
        perfume_form = PerfumeForm(request.POST, request.FILES)
        perfume_form.instance = perfume_form.save(commit=False)
        perfume_form.instance.author = request.user
        formset = PerfumeFragranceFormSet(request.POST)

        if not formset.is_valid():
            messages.error(
                request, f'Please correct the errors below and resubmit.')
            context = {
                'perfume_form': perfume_form,
                'perfume_fragrance_formset': formset,
                'form_errors': formset.errors
            }
            return render(request, 'perfume/perfume_form.html', context)

        if perfume_form.is_valid() and formset.is_valid():
            perfume_form.save()

            for form in formset:
                if form.cleaned_data != {} and form not in formset.deleted_forms:
                    form.instance.perfume = perfume_form.instance
                    form.save()
                    perfume_form.instance.fragrances.add(
                        form.instance.fragrance)
            perfume_form.save()
        messages.success(request, f'Your perfume has been created!')
        return redirect('perfume-home')

    else:
        perfume_form = PerfumeForm()
        formset = PerfumeFragranceFormSet(
            queryset=Perfume_Fragrance.objects.none())

    context = {
        'title': 'Create Perfume',
        'perfume_form': perfume_form,
        'perfume_fragrance_formset': formset
    }
    return render(request, 'perfume/perfume_form.html', context)


@login_required
def perfume_update_view(request, pk):
    perfume = get_object_or_404(Perfume, id=pk)
    if perfume.author != request.user:
        raise Http404()
    qs = perfume.perfume_fragrance_set.all()

    if request.method == 'POST':
        # get path to old image
        dir = os.path.abspath(os.path.dirname(__name__))
        filename = [dir] + perfume.image.url.split('/')
        old_image_url = os.path.join(*filename)

        perfume_form = PerfumeForm(request.POST, request.FILES, instance=perfume)
        formset = PerfumeFragranceFormSet(request.POST)

        if not formset.is_valid():
            messages.error(
                request, f'Please correct the errors below and resubmit.')
            context = {
                'perfume_form': perfume_form,
                'perfume_fragrance_formset': formset,
                'form_errors': formset.errors
            }
            return render(request, 'perfume/perfume_form.html', context)

        if perfume_form.is_valid():
            # formset.save()
            for form in formset:  # fragrances
                if form.is_valid() and form.cleaned_data != {} and form not in formset.deleted_forms:
                    form.instance.perfume = perfume_form.instance
                    form.save()
                    perfume_form.instance.fragrances.add(
                        form.instance.fragrance)

            # delete old image
            if os.path.isfile(old_image_url) and not old_image_url.endswith('default_perfume.jpg') and 'image' in request.FILES:
                os.remove(old_image_url)
            # perfume_form.calculate_nutritional_value()
            perfume_form.save()

            # to delete objects
            instances = formset.save(commit=False)
            for obj in formset.deleted_objects:
                obj.delete()
        messages.success(request, f'Your perfume has been updated!')
        return redirect('perfume-home')

    else:
        perfume_form = PerfumeForm(instance=perfume)
        formset = PerfumeFragranceFormSet(queryset=qs)

    context = {
        'title': 'Update Perfume',
        'perfume_form': perfume_form,
        'perfume_fragrance_formset': formset
    }
    return render(request, 'perfume/perfume_form.html', context)


class PerfumeDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):  # class based view
    model = Perfume
    success_url = '/'

    # user must pass test function in order to delete a perfume
    def test_func(self):
        perfume = self.get_object()
        if self.request.user == perfume.author:
            return True
        return False


def about(request):
    return render(request, 'perfume/about.html', {'title': 'About'})


@login_required
def fragrance_view(request):
    context = {'title': 'Fragrance Similarities'}
    if 'search-form' in request.POST:
        # get path to ai model
        dir = os.path.abspath(os.path.dirname(__name__))
        filename = dir + '\\ai\\word2vec.model'
        model = word2vec.Word2Vec.load(filename)
        fragrance = get_object_or_404(
            Fragrance, id=request.POST['fragrance'])
        context['ingr'] = fragrance
        fragrance = fragrance.name
        ingr = []
        comp = []
        if fragrance.lower().strip() not in model.wv.key_to_index:
            context['exists'] = False
        else:
            context['exists'] = True
            for ing, compatibility in model.wv.most_similar(positive=fragrance.lower().strip()):
                ingr.append(Fragrance.objects.filter(name__iexact=ing).first())
                comp.append(round(compatibility*100, 2))
            # Fragrance.objects.filter(name__in=ingr)
            context['similar'] = zip(ingr, comp)

    elif 'test-form' in request.POST:
        # get path to ai model
        dir = os.path.abspath(os.path.dirname(__name__))
        filename = dir + '\\ai\\word2vec.model'
        model = word2vec.Word2Vec.load(filename)
        ingr1 = get_object_or_404(Fragrance, id=request.POST['fragrance1'])
        ingr2 = get_object_or_404(Fragrance, id=request.POST['fragrance2'])
        context['ingr1'] = ingr1
        context['ingr2'] = ingr2
        if ingr1.name.lower().strip() not in model.wv.key_to_index or ingr2.name.lower().strip() not in model.wv.key_to_index:
            context['exists'] = False
        else:
            context['exists'] = True
            context['test_result'] = round(
                model.wv.similarity(ingr1.name.lower().strip(), ingr2.name.lower().strip())*100, 2)

    ingr_search = Fragrance.objects.all()

    context['ingr_search'] = ingr_search
    return render(request, 'perfume/fragrance_similarity.html', context)

fragrance_project/perfume/templates/perfume/about.html
{% extends "perfume/base.html" %}

{% block content %}
<h1>Privacy Policy for Fragrance Matcher</h1>

<p>At Fragrance Matcher one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Fragrance Matcher and how we use it.</p>

<p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>

<p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Fragrance Matcher. This policy is not applicable to any information collected offline or via channels other than this website. Our Privacy Policy was created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/">Free Privacy Policy Generator</a>.</p>

<h2>Consent</h2>

<p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>

<h2>Information we collect</h2>

<p>The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.</p>
<p>If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.</p>
<p>When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.</p>

<h2>How we use your information</h2>

<p>We use the information we collect in various ways, including to:</p>

<ul>
<li>Provide, operate, and maintain our website</li>
<li>Improve, personalize, and expand our website</li>
<li>Understand and analyze how you use our website</li>
<li>Develop new products, services, features, and functionality</li>
<li>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>
<li>Send you emails</li>
<li>Find and prevent fraud</li>
</ul>

<h2>Log Files</h2>

<p>Fragrance Matcher follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>




<h2>Advertising Partners Privacy Policies</h2>

<P>You may consult this list to find the Privacy Policy for each of the advertising partners of Fragrance Matcher.</p>

<p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on Fragrance Matcher, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>

<p>Note that Fragrance Matcher has no access to or control over these cookies that are used by third-party advertisers.</p>

<h2>Third Party Privacy Policies</h2>

<p>Fragrance Matcher's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>

<p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>

<h2>CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>

<p>Under the CCPA, among other rights, California consumers have the right to:</p>
<p>Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</p>
<p>Request that a business delete any personal data about the consumer that a business has collected.</p>
<p>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</p>
<p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

<h2>GDPR Data Protection Rights</h2>

<p>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
<p>The right to access – You have the right to request copies of your personal data. We may charge you a small fee for this service.</p>
<p>The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</p>
<p>The right to erasure – You have the right to request that we erase your personal data, under certain conditions.</p>
<p>The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.</p>
<p>The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.</p>
<p>The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</p>
<p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

<h2>Children's Information</h2>

<p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>

<p>Fragrance Matcher does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>
{% endblock content %}

fragrance_project/perfume/templates/perfume/home.html
{% extends "perfume/base.html" %}
{% load static %}


{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'perfume/css/perfume_list.css' %}">
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
{% endblock %}

{% block content %}
{% for rec in perfumes %}
    {% if forloop.counter0|divisibleby:"2" %}
        <article class="media content-section">
            <div class="media-body">
                <div class="card border-0" >
                    <div class="row no-gutters align-items-center">
                        <div class="col-md-8">
                            <div class="perfume-metadata d-flex">
                                <img class="rounded-circle perfume-img" src="{{ rec.author.profile.image.url }}" alt="{{ rec.author.username }}'s profile picture">
                                <p class="pe-3 pb-3 pt-3 author">{{ rec.author }}</p>
                                <small class="ms-auto p-3 text-muted ">{{ rec.date_posted|date:"F d, Y" }}</small>
                            </div>
                            <div class="card-body">
                                <h2><a class="perfume-title card-title" href="{% url 'perfume-detail' rec.id %}">{{ rec.name }}</a></h2>
                                <!-- <p class="perfume-content card-text">Target: {{ rec.target }}</p> -->
                                <p class="perfume-content card-text">{{ rec.description|slice:":255" }}...</p>
                                <!-- <p class="perfume-content card-text">Servings: {{ rec.servings }} | Cals: {{ rec.cals }}| Protein: {{ rec.protein }} | Carb: {{ rec.carb }}  | Fat: {{ rec.fat }} | Sugar: {{ rec.sugar }}</p> -->
                                <!-- <a href="{% url 'perfume-detail' rec.id %}" class="btn btn-outline-primary">See more</a> -->
                            </div>
                        </div>
                        <div class="col-md-4">
                            <img src="{{ rec.image.url }}" alt="Perfume image" class="rounded card-img"/>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    {% else %}
        <article class="media content-section">
            <div class="media-body">
                <div class="card border-0" >
                    <div class="row no-gutters align-items-center">
                        <div class="col-md-4">
                            <img src="{{ rec.image.url }}" alt="Perfume image" class="rounded card-img"/>
                        </div>
                        <div class="col-md-8">
                            <div class="perfume-metadata d-flex">
                                <small class="p-3 text-muted ">{{ rec.date_posted|date:"F d, Y" }}</small>
                                <img class="ms-auto rounded-circle perfume-img" src="{{ rec.author.profile.image.url }}" alt="{{ rec.author.username }}'s profile picture">
                                <p class="pe-3 pb-3 pt-3 author">{{ rec.author }}</p>
                            </div>
                            <div class="card-body">
                                <h2 class="text-end"><a class="perfume-title card-title" href="{% url 'perfume-detail' rec.id %}">{{ rec.name }}</a></h2>
                                <!-- <p class="perfume-content card-text text-end">Target: {{ rec.target }}</p> -->
                                <p class="perfume-content card-text text-end">{{ rec.description|slice:":255" }}...</p>
                                <!-- <p class="perfume-content card-text text-end">Servings: {{ rec.servings }} | Cals: {{ rec.cals }}| Protein: {{ rec.protein }} | Carb: {{ rec.carb }}  | Fat: {{ rec.fat }} | Sugar: {{ rec.sugar }}</p> -->
                                <!-- <a href="{% url 'perfume-detail' rec.id %}" class="btn btn-outline-primary">See more</a> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    {% endif %}
{% empty %}
    <div class="media-body">No perfumes yet 😳</div>
{% endfor %}

<!-- Pagination -->
{% if is_paginated %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li><a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            <!-- <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">&lt;</a>  -->
        {% else %}
            <li><a class="btn btn-outline-primary mb-4 disabled" href="?page=1">&laquo;</a></li>
        {% endif %}

        {% if page_obj.number|add:'-4' >= 1 %}
            <li><a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.number|add:'-4' }}">&hellip;</a></li>
        {% endif %}

        {% for nr in page_obj.paginator.page_range %}
            {% if page_obj.number == nr %}
                <li><a class="btn btn-primary mb-4" href="?page={{ nr }}">{{ nr }}</a></li>
            {% elif nr > page_obj.number|add:'-3' and nr < page_obj.number|add:'3' %}
                <li><a class="btn btn-outline-primary mb-4" href="?page={{ nr }}">{{ nr }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages >= page_obj.number|add:'4' %}
            <li><a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.number|add:'4' }}">&hellip;</a></li>
        {% endif %}
        
        {% if page_obj.has_next %}
            <!-- <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">&gt;</a> -->
            <li><a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
            <!-- <li><a class="btn btn-outline-primary mb-4 disabled" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li> -->
            <li><a class="btn btn-outline-primary mb-4 disabled" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
        {% endif %}
    </ul>
{% endif %}

{% endblock content %}

fragrance_project/perfume/templates/perfume/perfume_confirm_delete.html
{% extends "perfume/base.html" %}
{% load static %}


{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'perfume/css/login.css' %}">
{% endblock %}

{% block content %}
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 text-black">
    
            <div class="px-5 ms-xl-4">
                <span class="h1 fw-bold mb-0">Delete Perfume</span>
            </div>
    
            <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
    
                <form method="POST">
                    {% csrf_token %}  
    
                    <h3 class="fw-normal mb-3 pb-3">Are you sure you want to delete the perfume "{{ object.name }}"?</h3>
                    <div class="pt-1 mb-4">
                        <button class="btn btn-danger btn-lg w-100" type="submit">Yes, delete</button>
                        <a class="mt-3 btn btn-outline-secondary btn-lg w-100" href="{% url 'perfume-detail' object.id %}">No, cancel</a>
                    </div>
                </form>
            </div>
    
            </div>
            <div class="col-sm-6 px-0 d-none d-sm-block">
                <img src="{{ object.image.url }}" alt="Perfume image"/>
            </div>
        </div>
    </div>
  </section>
{% endblock content %}

fragrance_project/perfume/templates/perfume/perfume_form.html
{% extends "perfume/base.html" %}
{% load crispy_forms_tags %}
{% load static %} 

{% block content %}
<div class="content-section">
    <form id="perfume-form" method="POST" enctype="multipart/form-data">  <!-- enctype - used for saving img in the background -->
        {% csrf_token %}   <!-- added security for DJANGO -->
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Perfume</legend>
            {{ perfume_form|crispy }}  

            <legend class="border-bottom mt-4">Fragrances</legend>
            {{ perfume_fragrance_formset.management_form}}
            <div id="fragrance-form-list">
            {% for form in perfume_fragrance_formset %}
                <!-- <div class="fragrance-form"> -->
                <div>
                {% crispy form %}
                <!-- <button class="align-self-center btn btn-danger delete-image-form">-</button> -->
                </div>
            {% endfor %}
            </div>

            <div id="empty-form" class="hidden">{% crispy perfume_fragrance_formset.empty_form %}</div>
            <button id="add-more" type="button" class="btn btn-primary">+</button>
            </fieldset>
        <div class="form-group text-end mt-2 me-4">
            <button class="btn btn-outline-primary" type="submit">Post</button>
        </div>
    </form>
</div>
{% endblock content %}


{% block custom_js %}
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<script src="{% static 'perfume/js/perfume_add_fragrance.js' %}"></script>
<!-- <script src="{% static 'perfume/js/perfume_delete_fragrance.js' %}"></script> -->
{% endblock %}